### ISSUE TITLE
Generation should fail for incorrect discriminant

### ISSUE THREAD

**Issue by kafkas** [kafkas/typesync#95]
The following definition doesn't produce an error when it should. Instead, the generator produces a simple union.

```yaml
Pet:
  model: alias
  type:
    type: union
    discriminant: type
    variants:
      - type: object
        fields:
          type:
            type:
              type: literal
              value: dog
          breed:
            type: string
      - type: map
        of: string
```
